# EDSON YUDI TOMA - 9791305 #
# Exercise 2 #
# Find everyone who has a mother or a father and list both the person and the mother or father. Order by mother/father. Use the result variable name ?person, ?parent. #

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sim: <http://www.ifi.uio.no/INF3580/simpsons#>
PREFIX fam: <http://www.ifi.uio.no/INF3580/family#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?person ?parent WHERE {
    {?person rdf:type foaf:person .}
    UNION {?person fam:hasFather ?parent .}
    UNION {?person fam:hasMother ?parent .}
} ORDER BY ?parent