# EDSON YUDI TOMA - 9791305 #
# Exercise 5 #
# Find everyone older than 10. Order by age, oldest first. Output name and age. Result variable names: ?person, ?age. #

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sim: <http://www.ifi.uio.no/INF3580/simpsons#>
PREFIX fam: <http://www.ifi.uio.no/INF3580/family#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?person ?age WHERE {
    ?name foaf:name ?person .
    ?name foaf:age ?_age .
    FILTER (?_age > 10) .
    bind(xsd:integer(?_age) as ?age) .
} ORDER BY DESC(?age)